### ISSUE TITLE
Add rule book references

### ISSUE THREAD

**Issue by crobi** [crobi/dnd5e-quickref#1]
In case someone wants to look up the details

**Comment by SecretOnline** [comment]
I'll start working on this if you wish. I'm guessing the references should point to pages in the Players Handbook (possible DMG if needed, but I think the PH has all that's needed).

**Comment by crobi** [comment]
Yes, that would be awesome! I thought about adding a ` [PHB100]` at the end of each bullet point, to indicate page 100 in the player's handbook. But maybe you have a better idea. And while you're at it, feel free to add missing important information.

**Comment by SecretOnline** [comment]
My initial thoughts were to add a new element at the bottom of the modal which has all the references in one place. Most of the information for each action is in the same area of the book. 

Something like `PHB pg. XXX`, probably in the same style as the modal subheading.

**Comment by crobi** [comment]
> Most of the information for each action is in the same area of the book.

If this is true, then your idea is better, and the book references should probably be a separate property in the data files.
