### ISSUE TITLE
Ability to toggle between feet and squares

### ISSUE THREAD

**Issue by zanza00** [crobi/dnd5e-quickref#11]
We use a grid map to play and it would be awesome to implement a toggle between feet and squares in the movement.

In my fork i have done a search and replace of 5ft -> 1sq, 10ft -> 2sq but this solution is not so elegant.

**Comment by crobi** [comment]
See the second item in the FAQ: this is a minor change, and I don't want to make the code more complex to support such small features. What you did (fork and edit the data) is the preferred solution.
