### ISSUE TITLE
SVG icons instead of PNG?

### ISSUE THREAD

**Issue by jeffeoff** [crobi/dnd5e-quickref#14]
Has there been any thought about releaing a version using SVG icons for more crisp images instead of the background-image pngs currently in use?

**Comment by crobi** [comment]
SVG icons would have been nice. Do you see a difference, though? The PNGs are 512x512, even at 400% zoom on a high DPI display, I can't see any pixels.

I'd be happy to accept a PR that replaces the images. Preferably, it should be links and not inline SVGs, to make editing the reference sheet easy.

**Comment by jeffeoff** [comment]
I only saw the difference initially when I opened the html on my windows 10 machine and it defaulted to opening in Edge where the resizing is very jagged. In Chrome it looks much better.
