### ISSUE TITLE
Icons not visible when printed

### ISSUE THREAD

**Issue by sethladd** [crobi/dnd5e-quickref#15]
Thanks for the cards, but we can't see the icons when we print them out. The icons are transparent images with white pictures. And the background colors for the icons seem to be lost when printed. So, white image on white page isn't visible. :)

**Comment by crobi** [comment]
Did you turn on the printing of background images? Browsers don't print background colors by default.

**Comment by sethladd** [comment]
Ah, thanks for the tip. I turned on that option and now I can see the images.
