### ISSUE TITLE
Stabilize a creature

### ISSUE THREAD

**Issue by homiloko8** [crobi/dnd5e-quickref#20]
Just wanted to suggest that stabilizing a creature could be added to the list as an Action.
If you deem it redundant or unnecessary it's also fine, thanks for the great reference sheet.

**Comment by marquesarthur** [comment]
Add dying condition with disclaimer about rolling 1s and 20s and also how to stabilize a dying creature servers this purpose. 

If possible, I would like to contribute to this project. 
I can try to do this as my 1st contribution :)
