### ISSUE TITLE
Fork or resource use question.

### ISSUE THREAD

**Issue by Panglot** [crobi/dnd5e-quickref#26]
Hello, 
I know you added MIT license, but I feel that the correct thing is to ask before I do anything with your work. Is it OK to fork the project and/or use the icons? I love the idea and how you did it and I have something in my mind to make it bigger than that. Say more of the system implemented on multiple page site with references, connection and contents that will cover more of the DND system and make it easy to use on a mobile device and give good functionality for sessions. The smaller plan is to fork and expand your code, the bigger plan is to make it bigger with some modern framework and use mostly the data and the icons.

**Comment by crobi** [comment]
Thanks for asking!

Icons are from https://game-icons.net/, I'm not affiliated with them in any way.
Otherwise, feel free to use this project in any way you like :)

**Comment by Panglot** [comment]
Thank you. I will mention you for sure. If you are interested I can send you the result when it has at least something ready.
