### ISSUE TITLE
Add environmental effects

### ISSUE THREAD

**Issue by crobi** [crobi/dnd5e-quickref#7]
Since this project now includes conditions, it could include other environmental effects as well, such as:

- Light (bright, dim, darkness)
- Cover (none, half, 3/4, full)
- Obscurance (none, light, heavy)
- Sight (normal, darkvision, blindsight, truesight)

**Comment by SecretOnline** [comment]
Working on this right now. I would recommend leaving off merging #8 (that is, if you're going to) until I've finished this, as I'm a fool and committed to master rather than a branch.
